### PR TITLE
Using PRIORITY_MIN

### PR DESCRIPTION
**Pull request by Gustash**
- Changed persistent notification's priority to PRIORITY_MIN so that it doesn't clutter the user's status bar or lock screen.

### CODE REVIEW

**Comment by sabertooth07** [comment]
+1

**Comment by Yelrado** [comment]
+1

**Comment by yungshinlintw** [comment]
Hi Gustash,
Thanks a lot for your contribution. We are looking into this to reduce the clutter for the notifications.

**Comment by yungshinlintw** [comment]
Hi Gustash,
We have tested your changes and have taken your contribution. Thanks again for your contribution, and please definitely let us know if you have more ideas or suggestions!

**Comment by Gustash** [comment]
Will do :) thank you for accepting my contribution.

**Pull request merged**
